### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by bartclaeys** [joshwayne/jw-sketch-plugins#12]
Downloaded `split.cocoascript`, now what do I do with it to install it?

**Comment by joshwayne** [comment]
Hey @bartclaeys, you actually don't download the `.cocoascript` file directly. Unfortunately github screws up the new .sketchplugin format and thinks it's a folder and lets you see inside the plugin.

To get the plugins, just go back to the repo and download the whole thing as a zip. Open the zip file and you'll find the `Split Combine Text.sketchplugin` file in the Text folder.
