### ISSUE TITLE
Split Text to Layers no longer works

### ISSUE THREAD

**Issue by rohapa** [joshwayne/jw-sketch-plugins#2]
Split Text to Layers no longer works

**Comment by rohapa** [comment]
Anyway to fix this?

**Comment by rohapa** [comment]
Gives the error:
ReferenceError: Can't find variable: selection
line: 5
sourceURL: /Users/robertpaige/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin
column: 28


Script executed in 0.009484s

**Comment by joshwayne** [comment]
Sorry about the wait. I just updated the text plugins to the new plugin format so they should be working again. Cheers.
