### ISSUE TITLE
"Text" plugins subfolder doesn't show up in "Plugins" menu

### ISSUE THREAD

**Issue by giuseppebergman** [joshwayne/jw-sketch-plugins#6]
Hi, 
Since version 2.0, only "Layers" and "Pages" submenus shows up in Sketch Plugins/jw-sketch-plugins-master.

Thanks,

**Comment by joshwayne** [comment]
Are you talking about in Sketch or in Github? How are you installing the plugins to Sketch?

**Comment by giuseppebergman** [comment]
Hi, 
I'm talking about Sketch Plugins menu. 
I've installed the plugins by copying the "jw-sketch-plugins-master" folder into /Users/Me/Library/Application Support/com.bohemiancoding.sketch3/Plugins

UPDATE: Actually the Text submenu shows up at the root level of Sketch/Plugins menu, instead of as a child of "jw-sketch-plugins-master" entry (screenchots attached). 

BUT ! It works, so that's good for me. Thank you for your work!

![capture d ecran 2016-07-26 a 11h56 43](https://cloud.githubusercontent.com/assets/11982783/17133974/968e1666-5328-11e6-989e-74e3650ef3e0.png)

![capture d ecran 2016-07-26 a 12h00 16](https://cloud.githubusercontent.com/assets/11982783/17133963/917af7c0-5328-11e6-9470-d829e3fba17d.png)

**Comment by joshwayne** [comment]
Ah yeah, the text plugins are using Sketch's new plugin format. The new format lets you specify the name of the menu where they are located: https://github.com/joshwayne/jw-sketch-plugins/blob/master/Text/Split%20Combine%20Text.sketchplugin/Contents/Sketch/manifest.json#L24 

The layers and pages plugins are still using the old plugin format so they go to whatever folder they were dropped in. I'll be updating those to use the new format soon.

**Comment by giuseppebergman** [comment]
Ok, got it. Thank you for you quick updates, much appreciated!
