### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by bomberstudios** [joshwayne/jw-sketch-plugins#7]
Hi there.

As you probably know, `[MSTextLayer lineSpacing]` has been deprecated for a while, and it will be removed in Sketch v40. Please update your Plugin to use `[MSTextLayer lineHeight]` instead, or it won't work in the next release :)

**Comment by sogen** [comment]
Waiting for 40 😀 👍

**Comment by joshwayne** [comment]
Hey @bomberstudios, is there a reason why `lineHeight` doesn't work the same as `lineSpacing`? I can't seem to get it to work in v39 or v40. There's also no reference to lineHeight in the MSTextLayer documentation: http://developer.sketchapp.com/reference/class/MSTextLayer/

**Comment by joshwayne** [comment]
@bomberstudios I isolated the problem. `lineHeight` returns 0 if the “Line Spacing” field is empty. I submitted a bug report and I'll have to hack it in the meantime.

**Comment by sogen** [comment]
Hi, any updates?

**Comment by idoshavit** [comment]
Hi. Does not work for me on 40 :(? Very useful plug-in please fix.

**Comment by giuseppebergman** [comment]
Same here, broken in 40.1. A fix would be hugely appreciated, your plug-in rocks!

**Comment by stevelewis** [comment]
I would also give mad props to a fix for this.

**Comment by sogen** [comment]
@stevelewis did the replace on file **split.cocoascript**,  lines **27** and **36** but still no luck, can you share you file, thanks

**Comment by joshwayne** [comment]
Sorry for the wait @sogen @idoshavit @giuseppebergman @stevelewis. The day job has been keeping me really busy. The plugin is now updated!

**Comment by username1290** [comment]
Huge thanks Josh :)

**Comment by giuseppebergman** [comment]
Thanks a lot!

**Comment by idoshavit** [comment]
thnx!
