### ISSUE TITLE
Only works with paragraph lines?

### ISSUE THREAD

**Issue by giuseppebergman** [joshwayne/jw-sketch-plugins#8]
Hi, and thanks again for this very nice little plugin.
I waw wondering, is it normal that it only detect a line to split if said line starts a paragraph (= created by pressing Enter)? 
It would be nice for it to work with every linebreak, even those created by resizing a text block (by pulling its handles vs. by pressing Enter).

**Comment by username1290** [comment]
ahh, clever! had never thought that

**Comment by joshwayne** [comment]
Unfortunately, yes, it only works with line breaks. When text continues on the next line, it's call a line wrap and not a line break. Line breaks are easy to detect but lines wraps would be really difficult. I'm not a good enough programmer to figure out how to detect line wraps in Sketch. I think that's a project for a real developer :)

**Comment by giuseppebergman** [comment]
Thank you for your answer (and for the vocabulary :) 
I had no idea of the difficulty. And thanks again for the plugin!
