### ISSUE TITLE
Split/Combine Text Layers stopped working on 40.1

### ISSUE THREAD

**Issue by hankisthatyou** [joshwayne/jw-sketch-plugins#9]
Split Text Lines to Layers: Will duplicate the existing text layers instead of breaking into lines.
Combine Text Layers: Will delete layers instead combining text layers.

**Comment by joshwayne** [comment]
Did you download the latest version? It was updated a couple days ago.

**Comment by hankisthatyou** [comment]
Ah didn't realize you updated it, it's now working perfectly! Thanks for the update!
